# Generated by Django 5.1.3 on 2024-12-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='class_type',
        ),
        migrations.CreateModel(
            name='TaskClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_type_tasks', to='app.classtype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_class_types', to='app.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='class_types',
            field=models.ManyToManyField(through='app.TaskClassType', to='app.classtype'),
        ),
    ]
