# Generated by Django 5.1.3 on 2024-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_class_type_taskclasstype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtype',
            name='price',
        ),
        migrations.AddField(
            model_name='taskclasstype',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Доступные места'),
        ),
    ]
