# Generated by Django 5.1.3 on 2024-12-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_classtype_price_taskclasstype_available_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='price',
        ),
    ]
