# Generated by Django 5.1.3 on 2024-12-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_task_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='nos',
        ),
    ]
