# Generated by Django 5.1.3 on 2024-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customuser_created_at_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
