# Generated by Django 5.1.3 on 2024-12-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_token',
        ),
    ]
