# Generated by Django 5.1.3 on 2024-12-15 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='classtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classtype',
            name='name',
            field=models.CharField(default='Без имени', max_length=50, verbose_name='Название класса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskclasstype',
            name='available_seats',
            field=models.PositiveIntegerField(default=10, verbose_name='Доступные места'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskclasstype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('number', models.PositiveIntegerField(verbose_name='Номер места')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('sold', 'Продано')], default='available', max_length=10, verbose_name='Статус')),
                ('task_class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.taskclasstype')),
            ],
        ),
    ]
