# Generated by Django 5.1.3 on 2024-12-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_seat_status_remove_seat_task_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='class_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.classtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.task'),
            preserve_default=False,
        ),
    ]
