# Generated by Django 5.1.3 on 2024-12-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_seat_class_type_seat_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='task',
        ),
        migrations.AddField(
            model_name='seat',
            name='task_class_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.taskclasstype'),
            preserve_default=False,
        ),
    ]
